name: Build EXE

on:
  push:

jobs:
  build:

    runs-on: windows-latest

    steps:

    - name: Checkout Repo
      uses: actions/checkout@v4

    - name: Setup Python
      uses: actions/setup-python@v5
      with:
        python-version: "3.11"

    - name: Install Dependencies
      run: |
        pip install pyinstaller
        if exist requirements.txt pip install -r requirements.txt

    - name: Build EXE
      run: |
        pyinstaller --onefile --clean --name Armageddon main_v2.py

    - name: Upload EXE
      uses: actions/upload-artifact@v4
      with:
        name: Armageddon
        path: dist/Armageddon.exe
